-- #THIS IS A COMMAND FOR CREATING A TABLE IN YOUR DATABASE IN MYSQL.
-- #USE <DATABASE_NAME>; #THIS COMMAND WILL NOW USE DATABASE FOR CREATING TABLE WHICH IS PROVIDED BY USER.
-- #CREATE TABLE <TABLE_NAME>(
-- #COLUMN_NAME    DATA TYPE[size] CONSTRAINTS,
-- #COLUMN_NAME    DATA TYPE[size] CONSTRAINTS,
-- #COLUMN_NAME    DATA TYPE[size] CONSTRAINTS,
-- #);



CREATE DATABASE Python;
SHOW DATABASES;