#THIS COMMAND IS USED FOR ENTERING DATA INTO TABLES IN YOUR DATABASE.
#1--TO INSERT DATA INTO TO ALL COLUMNS OF THE TABLE.
#INSERT INTO <TABLE_NAME> VALUES(value1,value2,value3,......,valueN)



#2--TO INSERT DATA INTO SPECIFIC COLUMNS OF THE TABLE.
#INSERT INTO <TABLE_NAME> (column1,column2,.......,columnN) VALUES(value1,value2,value3,......,valueN)

